/**
 * Role-to-operation permission table.
 *
 * This is the single source of truth for all ED access control.
 * IMPORTANT: Permissions are enforced in the service layer (JS) AND in Firestore rules.
 * Hiding/showing UI buttons is secondary only.
 *
 * ⚠️  Prototype only — role management must be hardened before any clinical use.
 */

import { ED_ROLE, ED_OPERATION } from '../types/enums.js';

const {
  REGISTER_ENCOUNTER, RECORD_ASSESSMENT, ACTIVATE_EMERGENCY,
  ACKNOWLEDGE_EMERGENCY, RESOLVE_EMERGENCY, CALL_PATIENT,
  START_CONSULTATION, COMPLETE_ENCOUNTER, CANCEL_ENCOUNTER,
  RECORD_REASSESSMENT, PERFORM_OVERRIDE, MANAGE_ROLES,
  VIEW_AUDIT_LOG, VIEW_QUEUE, RUN_SIMULATOR, RESET_SIMULATOR,
} = ED_OPERATION;

/**
 * Map of role → Set of allowed operations.
 * Only ADMINISTRATOR implicitly has every operation.
 */
export const ROLE_PERMISSIONS = Object.freeze({
  [ED_ROLE.REGISTRATION_STAFF]: new Set([
    REGISTER_ENCOUNTER,
    VIEW_QUEUE,
  ]),

  [ED_ROLE.TRIAGE_CLINICIAN]: new Set([
    REGISTER_ENCOUNTER,
    RECORD_ASSESSMENT,
    RECORD_REASSESSMENT,
    CALL_PATIENT,
    VIEW_QUEUE,
  ]),

  [ED_ROLE.EMERGENCY_CLINICIAN]: new Set([
    REGISTER_ENCOUNTER,
    RECORD_ASSESSMENT,
    RECORD_REASSESSMENT,
    ACTIVATE_EMERGENCY,
    ACKNOWLEDGE_EMERGENCY,
    RESOLVE_EMERGENCY,
    CALL_PATIENT,
    START_CONSULTATION,
    COMPLETE_ENCOUNTER,
    VIEW_QUEUE,
  ]),

  [ED_ROLE.FLOW_COORDINATOR]: new Set([
    REGISTER_ENCOUNTER,
    RECORD_ASSESSMENT,
    RECORD_REASSESSMENT,
    ACTIVATE_EMERGENCY,
    ACKNOWLEDGE_EMERGENCY,
    RESOLVE_EMERGENCY,
    CALL_PATIENT,
    START_CONSULTATION,
    COMPLETE_ENCOUNTER,
    CANCEL_ENCOUNTER,
    PERFORM_OVERRIDE,
    VIEW_QUEUE,
    RUN_SIMULATOR,
    RESET_SIMULATOR,
  ]),

  [ED_ROLE.SUPERVISOR]: new Set([
    REGISTER_ENCOUNTER,
    RECORD_ASSESSMENT,
    RECORD_REASSESSMENT,
    ACTIVATE_EMERGENCY,
    ACKNOWLEDGE_EMERGENCY,
    RESOLVE_EMERGENCY,
    CALL_PATIENT,
    START_CONSULTATION,
    COMPLETE_ENCOUNTER,
    CANCEL_ENCOUNTER,
    PERFORM_OVERRIDE,
    VIEW_AUDIT_LOG,
    VIEW_QUEUE,
    RUN_SIMULATOR,
    RESET_SIMULATOR,
  ]),

  [ED_ROLE.ADMINISTRATOR]: new Set(Object.values(ED_OPERATION)),

  [ED_ROLE.AUDITOR]: new Set([
    VIEW_AUDIT_LOG,
    VIEW_QUEUE,
  ]),
});
